### ISSUE TITLE
unable to open file: 'densenet2_036.hdf5' No such file or directory

### ISSUE THREAD

**Issue by mahmoodabed** [hkhats95/Abnormality_detection_in_Radiographs#1]
This issue is in train_classifier_densenet.ipynb and it could be in other notebooks.

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-15-88024c262947> in <module>
      7 s = reset_tf_session()
      8 last_finished_epoch = 36
----> 9 model = load_model(model_filename.format(epoch=last_finished_epoch))
     10 

C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\saving.py in load_model(filepath, custom_objects, compile)
    415     model = None
    416     opened_new_file = not isinstance(filepath, h5py.Group)
--> 417     f = h5dict(filepath, 'r')
    418     try:
    419         model = _deserialize_model(f, custom_objects, compile)

C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\io_utils.py in __init__(self, path, mode)
    184             self._is_file = False
    185         elif isinstance(path, str):
--> 186             self.data = h5py.File(path, mode=mode)
    187             self._is_file = True
    188         elif isinstance(path, dict):

C:\ProgramData\Anaconda3\lib\site-packages\h5py\_hl\files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, **kwds)
    392                 fid = make_fid(name, mode, userblock_size,
    393                                fapl, fcpl=make_fcpl(track_order=track_order),
--> 394                                swmr=swmr)
    395 
    396             if swmr_support:

C:\ProgramData\Anaconda3\lib\site-packages\h5py\_hl\files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    168         if swmr and swmr_support:
    169             flags |= h5f.ACC_SWMR_READ
--> 170         fid = h5f.open(name, flags, fapl=fapl)
    171     elif mode == 'r+':
    172         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (unable to open file: name = 'densenet2_036.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by hkhats95** [comment]
Please read carefully before running the cells.
